modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="dungeons_arise_seven_seas"
version="1.0.1"
displayName="When Dungeons Arise: Seven Seas"
displayURL="https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise"
logoFile="wda_seven_seas.png"
authors="Zephyrusj, Aurelj"
description='''
Elegant - and likely dangerous - structures and roguelike dungeons to lose yourself in...
'''

[[dependencies.dungeons_arise_seven_seas]] #optional
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="SERVER"

[[dependencies.dungeons_arise_seven_seas]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.21)"
ordering="NONE"
side="SERVER"